/**
 * Writes migrations/0001_auth.sql from Better Auth's own schema, using an
 * in-memory SQLite database. Run after upgrading better-auth:
 *   node apps/admin/scripts/generate-auth-schema.ts
 */
import { writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { getMigrations } from "better-auth/db/migration";
import { authOptions } from "../src/auth-options.ts";

const { compileMigrations } = await getMigrations({
  ...authOptions({ googleClientId: "x", googleClientSecret: "x" }),
  database: new DatabaseSync(":memory:"),
});
const sql = await compileMigrations();
const out = new URL("../migrations/0001_auth.sql", import.meta.url);
writeFileSync(
  out.pathname,
  `-- Generated by scripts/generate-auth-schema.ts from better-auth. Do not edit by hand.\n${sql}\n`,
);
console.log(`wrote ${out.pathname}`);
